services:
  app:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - "./notebook:/home/john/notebooks"
    command: "jupyter lab --ip=0.0.0.0 --no-browser --port=8888 --notebook-dir=/home/john/notebooks --ServerApp.password=${ACCESS_TOKEN}"
