version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - "./notebook:/home/jupyter/notebook"
    command: "jupyter lab --ip=0.0.0.0 --no-browser --port=8888 --notebook-dir=/home/jupyter/notebook --ServerApp.password=${ACCESS_TOKEN}"
